# .travis.yml using container-based infrastructure

# use c as catch-all language
language: c

# use containers
sudo: false

# only run for pushes to master branch
branches:
  only:
  - master
  - devel

# install R: use r-packages-precise (https://cran.r-project.org/bin/linux/ubuntu/precise/)
# as source which is white listed (https://github.com/travis-ci/apt-source-whitelist/)
## https://github.com/travis-ci/apt-package-whitelist
## to see the current versions: http://packages.ubuntu.com/precise/text/pandoc
addons:
  apt:
    sources:
    - r-packages-precise
    packages:
    - r-base-dev
    - r-recommended
    - libcurl3


# cache local R libraries directory:
cache:
  directories:
    - ~/Rlib
# Be strict when checking our package
warnings_are_errors: false

# Install binary pandoc from Rstudio
before_install:
  - export PATH="$HOME/pandoc:$PATH"
  - mkdir $HOME/pandoc
  - curl -O https://s3.amazonaws.com/rstudio-buildtools/pandoc-1.12.3.zip
  - unzip -j pandoc-1.12.3.zip pandoc-1.12.3/linux/debian/x86_64/pandoc
      -d $HOME/pandoc
  - chmod +x $HOME/pandoc/pandoc
  - pandoc --version

# install the package and dependencies:
# - create directory for R libraries (if not already exists)
# - create .Renviron with location of R libraries
# - define R repository in .Rprofile
# - add .travis.yml to .Rbuildignore
# - install devtools if not already installed
# - install covr if not already installed
# - update all installed packages
# - install package with dependencies
install:
  - mkdir -p ~/Rlib
  - echo 'R_LIBS=~/Rlib' > ~/.Renviron
  - echo 'options(repos = c(CRAN="http://cran.rstudio.com", DRAT="http://sahilseth.github.io/drat")' > .Rprofile
  - cat .Rprofile; Rscript -e 'options("repos");print(.libPaths())'
  - Rscript -e 'if(!"devtools" %in% rownames(installed.packages())) { install.packages("devtools", dependencies = TRUE) }'
  - Rscript -e 'if(!"covr" %in% rownames(installed.packages())) { install.packages("covr", dependencies = TRUE) }'
  - Rscript -e 'devtools::install_deps(pkg = ".", dependencies = TRUE)'
  - Rscript -e 'install.packages("staticdocs")'
  - Rscript -e 'install.packages("packagedocs")'
  - Rscript -e 'install.packages("params")'
  - Rscript -e 'update.packages(ask = FALSE, instlib = "~/Rlib")' ## update all packages !
   
#  - Rscript -e 'devtools::install_github("sahilseth/staticdocs")'
#  - Rscript -e 'devtools::install_github("sahilseth/packagedocs")'
#  - Rscript -e 'devtools::install_github("sahilseth/params")'

# Build and check package
script:
  - R CMD build . --no-build-vignettes --no-manual
  - PKG_FILE_NAME=$(ls -1t *.tar.gz | head -n 1)
  - R CMD check "${PKG_FILE_NAME}" --no-build-vignettes --no-manual --as-cran rpack
  
#  - Rscript -e 'devtools::build()'

after_success:
  - R CMD INSTALL .
  - Rscript -e 'covr::codecov()'
  - test $TRAVIS_PULL_REQUEST == "false" && test $TRAVIS_BRANCH == "devel" && bash misc/deploy2.sh
