# a good example: https://github.com/OuhscBbmc/REDCapR/blob/master/.travis.yml
language: r
sudo: required

# Be strict when checking our package
warnings_are_errors: false

# System dependencies for HTTP calling
# http://docs.travis-ci.com/user/languages/r/

# R
#r_check_args: --timings --as-cran --no-install
r_check_args: --no-build-vignettes --no-manual --as-cran rpack

r_packages:
  - rmarkdown

#r_binary_packages:
#  - stringi
#  - digest
#  - yaml
#  - bitops
#  - markdown
#  - caTools
#  - lazyeval
#  - openxlsx
#  - plyr
#  - testthat
#  - reshape2
#  - scales

## Following to take care of stringi error from travis (temporary)
r_github_packages:
  - sahilseth/params
  - hadley/staticdocs
  - sahilseth/readthedocs
  - jimhester/covr

after_success:
  - Rscript -e 'covr::codecov()'
  - Rscript misc/deploy.R
  - test $TRAVIS_PULL_REQUEST == "false" && test $TRAVIS_BRANCH == "devel" && bash misc/deploy.sh
env:
  global:
    - secure: "KDZW6kR9QiG1+fAOrFNMGnAPMkT+cTeiKG95SgB7az+/Y9I6h/Ss9BSCChGpS/DsDsMO159t4kBmPhjj/1Ath6eGDMpHESkX2H/HnsP3/puG8AONiJaYsQ4/G5IQ+N/JZXHnhN2tCznHbHg6uUjAD8L3li4Pnwo8FAxp76xz38GdnDhP/vy/numq6pTa71zCVxLn1F3WC9OpsJg178b6EddLzfnf4nIumXQag+spKDxxInYqfb6nNU+DcYviBWiZWS1IXdBgyWLek+wAvM0vfHwRFMPMEzQngVEUFZ17WKgyZIHGfPsEm/AUuwUaBKwvS4gU+PQNd3gPCiTJuUShtgW5MJqgBHhW5vbYxfVjLl+2dUb05+t3VaqOHLtLNHENASkPGwhZc3sMaNw5y0iFtK32tXVGbuHm5Uqplo+r2hgNaW+hlwg6Cq03ltYDisitP1/AZsSgg6j9tkYMKhf1gMa+OqJUV+01aD81l692PkaiXMiLqVuu2aP8wHdwsgwbV6wC8eC6/jK3Z9F1wHIxhizdIWPoshZQ7Y9jXvUkLGPtzUsZI6ioODvbPqjzdiSHCM6UqB17RWBIR/BVZZ1SA+PSQAuM9iNpUGHcfMusrjCpywiH1KX6aAkkcxF1NKL5lId4llCEBv2gzRZqYbCXfdFnYI+NZRmFJ90kjSsNcLE="
  
