# a good example: https://github.com/OuhscBbmc/REDCapR/blob/master/.travis.yml
language: r

# Be strict when checking our package
warnings_are_errors: false

# System dependencies for HTTP calling
# http://docs.travis-ci.com/user/languages/r/

# R 
#r_check_args: --timings --as-cran
#r_check_args: --no-install

## Following to take care of stringi error from travis (temporary)
#r_github_packages:
#  - Rexamine/stringi
